import express from"express";import{allowRoles,requireAuth}from"../middleware/auth.js";import{uploadCertificate,uploadCourseAssets}from"../middleware/upload.js";import{coursePayload,saveCourseAssets}from"../course-assets.js";import{AuditLog,Certificate,Course,SiteSetting,Student,User}from"../models/index.js";import{asyncRoute,normalizeCode,pagination,recordAudit,saveCertificateFile}from"../utils.js";const router=express.Router();router.use(requireAuth);router.get("/dashboard",asyncRoute(async(_req,res)=>{const[students,courses,certificates,recentActivity]=await Promise.all([Student.countDocuments({status:"active"}),Course.countDocuments({status:"published"}),Certificate.countDocuments({status:"verified"}),AuditLog.find().sort({createdAt:-1}).limit(8).lean()]);res.json({students,courses,certificates,recentActivity})}));
const list=(Model,defaultLimit=20)=>asyncRoute(async(req,res)=>{const{page,limit,skip}=pagination(req.query,defaultLimit),filter={};if(req.query.status)filter.status=req.query.status;if(req.query.q)filter.$or=[{code:{$regex:String(req.query.q),$options:"i"}},{studentId:{$regex:String(req.query.q),$options:"i"}},{certificateNumber:{$regex:String(req.query.q),$options:"i"}},{"title.ar":{$regex:String(req.query.q),$options:"i"}},{"title.en":{$regex:String(req.query.q),$options:"i"}},{"fullName.ar":{$regex:String(req.query.q),$options:"i"}},{"fullName.en":{$regex:String(req.query.q),$options:"i"}}];const[items,total]=await Promise.all([Model.find(filter).sort({createdAt:-1}).skip(skip).limit(limit).lean(),Model.countDocuments(filter)]);res.json({items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}})});
router.get("/courses",list(Course));
router.post("/courses",allowRoles("super_admin","admin","editor"),uploadCourseAssets,asyncRoute(async(req,res)=>{
  const data=coursePayload(req);
  if(!data.code||!data.slug||!data.title?.ar||!data.title?.en)return res.status(400).json({message:"Bilingual title, code and slug required"});
  const uploads=await saveCourseAssets(req.files);
  let item;
  try { item=await Course.create({...data,...uploads.fields,code:normalizeCode(data.code)}); }
  catch(error){await uploads.cleanup();throw error;}
  await recordAudit(req,"course.create","Course",item.id);
  res.status(201).json(item);
}));
router.patch("/courses/:id",allowRoles("super_admin","admin","editor"),uploadCourseAssets,asyncRoute(async(req,res)=>{
  const data=coursePayload(req);
  const uploads=await saveCourseAssets(req.files);
  let item;
  try {item=await Course.findByIdAndUpdate(req.params.id,{$set:{...data,...uploads.fields}},{new:true,runValidators:true});}
  catch(error){await uploads.cleanup();throw error;}
  if(!item){await uploads.cleanup();return res.status(404).json({message:"Not found"});}
  await recordAudit(req,"course.update","Course",item.id);
  res.json(item);
}));
router.delete("/courses/:id",allowRoles("super_admin","admin"),asyncRoute(async(req,res)=>{const item=await Course.findByIdAndUpdate(req.params.id,{status:"archived"},{new:true});if(!item)return res.status(404).json({message:"Not found"});await recordAudit(req,"course.archive","Course",item.id);res.json(item)}));
router.get("/students",list(Student));router.post("/students",allowRoles("super_admin","admin","editor"),asyncRoute(async(req,res)=>{if(!req.body.studentId||!req.body.fullName?.ar||!req.body.fullName?.en)return res.status(400).json({message:"Student ID and bilingual name required"});const item=await Student.create({...req.body,studentId:normalizeCode(req.body.studentId)});await recordAudit(req,"student.create","Student",item.id);res.status(201).json(item)}));router.patch("/students/:id",allowRoles("super_admin","admin","editor"),asyncRoute(async(req,res)=>{delete req.body._id;const item=await Student.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!item)return res.status(404).json({message:"Not found"});await recordAudit(req,"student.update","Student",item.id);res.json(item)}));router.delete("/students/:id",allowRoles("super_admin","admin"),asyncRoute(async(req,res)=>{const item=await Student.findByIdAndUpdate(req.params.id,{status:"archived",publicProfile:false},{new:true});if(!item)return res.status(404).json({message:"Not found"});res.json(item)}));
router.get("/certificates",list(Certificate));router.post("/certificates",allowRoles("super_admin","admin","editor"),uploadCertificate,asyncRoute(async(req,res)=>{const student=await Student.findOne({studentId:normalizeCode(req.body.studentId)});if(!student||!req.body.certificateNumber||!req.body.courseTitleAr||!req.body.courseTitleEn||!req.body.issueDate)return res.status(400).json({message:"Required certificate data missing"});const item=await Certificate.create({certificateNumber:normalizeCode(req.body.certificateNumber),student:student._id,course:req.body.courseId||undefined,courseTitle:{ar:req.body.courseTitleAr,en:req.body.courseTitleEn},issueDate:req.body.issueDate,grade:{ar:req.body.gradeAr||"",en:req.body.gradeEn||""},status:req.body.status||"verified",...await saveCertificateFile(req.file)});await recordAudit(req,"certificate.create","Certificate",item.id);res.status(201).json(item)}));router.patch("/certificates/:id",allowRoles("super_admin","admin","editor"),asyncRoute(async(req,res)=>{delete req.body._id;const item=await Certificate.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});item?res.json(item):res.status(404).json({message:"Not found"})}));router.delete("/certificates/:id",allowRoles("super_admin","admin"),asyncRoute(async(req,res)=>{const item=await Certificate.findByIdAndUpdate(req.params.id,{status:"revoked"},{new:true});item?res.json(item):res.status(404).json({message:"Not found"})}));
router.get("/settings",asyncRoute(async(_req,res)=>res.json(await SiteSetting.findOne({key:"platform"}).lean()||{})));router.put("/settings",allowRoles("super_admin","admin"),asyncRoute(async(req,res)=>{delete req.body._id;delete req.body.key;const item=await SiteSetting.findOneAndUpdate({key:"platform"},{...req.body,key:"platform"},{upsert:true,new:true,runValidators:true});await recordAudit(req,"settings.update","SiteSetting",item.id);res.json(item)}));router.get("/activity",allowRoles("super_admin","admin"),list(AuditLog,30));router.get("/administrators",allowRoles("super_admin"),asyncRoute(async(_req,res)=>res.json(await User.find().select("name email role active lastLoginAt createdAt").lean())));export default router;
